apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# List of resources to include in this base
resources:
- deployment.yaml

# Common labels to add to all resources and selectors
commonLabels:
  app: website

# Common annotations to add to all resources
commonAnnotations:
  note: "This is a website resource"
